class UnexpectedResultError(Exception):
    pass


class Tests4PySubjectException(Exception):
    pass
